# -*- coding: utf-8 -*-
"""визуализация.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vwBL-ROtYH6kblrJe1cCM2iwDIATFcyF
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
from google.colab import files

try:
    df_mar
except NameError:
    print("Загрузите файл с браками (например, data (7).xls)")
    uploaded = files.upload()
    filename = list(uploaded.keys())[0]

    def read_demography(filepath, value_name):
        raw = pd.read_excel(filepath, sheet_name="Данные", header=None)
        years = raw.iloc[2, 1:].values
        months = raw.iloc[3, 1:].values

        cur_year = None
        filled_years = []
        for y in years:
            if pd.notna(y):
                cur_year = int(y)
            filled_years.append(cur_year)

        month_dict = {
            'январь':1, 'февраль':2, 'март':3, 'апрель':4, 'май':5, 'июнь':6,
            'июль':7, 'август':8, 'сентябрь':9, 'октябрь':10, 'ноябрь':11, 'декабрь':12
        }

        dates = []
        for y, m in zip(filled_years, months):
            if y is not None and pd.notna(m):
                m_str = str(m).strip().lower()
                month_num = month_dict.get(m_str, 1)
                dates.append(datetime(y, month_num, 1))
            else:
                dates.append(None)

        data = raw.iloc[4:].copy()
        data.columns = ["region"] + dates
        data.set_index("region", inplace=True)
        data.dropna(how="all", inplace=True)

        long_data = data.stack().reset_index()
        long_data.columns = ["region", "date", value_name]
        long_data[value_name] = pd.to_numeric(long_data[value_name], errors='coerce')
        long_data = long_data.dropna(subset=[value_name])
        long_data["date"] = pd.to_datetime(long_data["date"])
        return long_data

    df_mar = read_demography(filename, "marriages")
    print(f"Загружено {len(df_mar)} записей о браках")

rus2020 = df_mar[df_mar["date"].dt.year == 2020].groupby(df_mar["date"].dt.month)["marriages"].sum()
rus2020 = rus2020.sort_index()

months_ru = ['Янв','Фев','Мар','Апр','Май','Июн','Июл','Авг','Сен','Окт','Ноя','Дек']
x = range(1, 13)
y = rus2020.values

max_idx = np.argmax(y)
min_idx = np.argmin(y)

colors = ['#3498db'] * 12
colors[max_idx] = '#2ecc71'
colors[min_idx] = '#e74c3c'

plt.figure(figsize=(12, 6))
bars = plt.bar(x, y, color=colors, edgecolor='black', linewidth=0.8)

for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height + max(y)*0.02,
             f'{int(height):,}'.replace(',', ' '), ha='center', va='bottom', fontsize=9)

plt.xticks(x, months_ru, fontsize=11)
plt.xlabel('Месяц', fontsize=12)
plt.ylabel('Число браков', fontsize=12)
plt.title('Количество браков в 10 самых населенных регионах России за 2020 год', fontsize=14, fontweight='bold')
plt.grid(axis='y', linestyle='--', alpha=0.7)

from matplotlib.patches import Patch
legend_elements = [
    Patch(facecolor='#2ecc71', edgecolor='black', label='Максимум'),
    Patch(facecolor='#e74c3c', edgecolor='black', label='Минимум'),
    Patch(facecolor='#3498db', edgecolor='black', label='Остальные месяцы')
]
plt.legend(handles=legend_elements, loc='upper right')

plt.tight_layout()
plt.show()

print(f"Максимум браков: {months_ru[max_idx]} – {int(y[max_idx]):,}".replace(',', ' '))
print(f"Минимум браков: {months_ru[min_idx]} – {int(y[min_idx]):,}".replace(',', ' '))

region_keywords = {
    "Москва": "Город Москва",
    "Санкт-Петербург": "Город Санкт-Петербург",
    "Дагестан": "Республика Дагестан",
    "Башкортостан": "Республика Башкортостан",
    "Татарстан": "Республика Татарстан"
}

found = {}
for kw, display_name in region_keywords.items():
    matches = [r for r in df_mar["region"].unique() if kw in r]
    if matches:
        found[display_name] = matches[0]

if len(found) >= 2:
    h2_data = {}
    for display, actual in found.items():
        reg_data = df_mar[(df_mar["region"] == actual) & (df_mar["date"] >= "2020-07-01") & (df_mar["date"] <= "2020-12-31")]
        h2_data[display] = reg_data.groupby("date")["marriages"].sum().reset_index()

    all_reg = None
    for name, df_reg in h2_data.items():
        df_reg = df_reg.rename(columns={"marriages": name})
        if all_reg is None:
            all_reg = df_reg
        else:
            all_reg = all_reg.merge(df_reg, on="date", how="outer")

    plt.figure(figsize=(14, 7))
    for col in all_reg.columns[1:]:
        plt.plot(all_reg["date"], all_reg[col], marker='o', linewidth=2, markersize=6, label=col)

    plt.ylabel('Число браков', fontsize=12)
    plt.title('Динамика браков в регионах (июль–декабрь 2020)', fontsize=14, fontweight='bold')
    plt.legend(bbox_to_anchor=(1.05, 1), loc='upper left')
    plt.grid(True, linestyle='--', alpha=0.7)

    dates_h2 = all_reg["date"].values
    month_names_ru = {1:'Янв', 2:'Фев', 3:'Мар', 4:'Апр', 5:'Май', 6:'Июн',
                      7:'Июл', 8:'Авг', 9:'Сен', 10:'Окт', 11:'Ноя', 12:'Дек'}
    labels = [f"{month_names_ru[pd.to_datetime(d).month]} {pd.to_datetime(d).year}" for d in dates_h2]
    plt.xticks(dates_h2, labels, rotation=45)

    plt.tight_layout()
    plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
from scipy.stats import linregress
from google.colab import files
from matplotlib.patches import Patch

try:
    df_mar
except NameError:
    print("Загрузите файл с браками (например, data (7).xls)")
    uploaded = files.upload()
    filename = list(uploaded.keys())[0]

    def read_demography(filepath, value_name):
        raw = pd.read_excel(filepath, sheet_name="Данные", header=None)
        years = raw.iloc[2, 1:].values
        months = raw.iloc[3, 1:].values

        cur_year = None
        filled_years = []
        for y in years:
            if pd.notna(y):
                cur_year = int(y)
            filled_years.append(cur_year)

        month_dict = {
            'январь':1, 'февраль':2, 'март':3, 'апрель':4, 'май':5, 'июнь':6,
            'июль':7, 'август':8, 'сентябрь':9, 'октябрь':10, 'ноябрь':11, 'декабрь':12
        }

        dates = []
        for y, m in zip(filled_years, months):
            if y is not None and pd.notna(m):
                m_str = str(m).strip().lower()
                month_num = month_dict.get(m_str, 1)
                dates.append(datetime(y, month_num, 1))
            else:
                dates.append(None)

        data = raw.iloc[4:].copy()
        data.columns = ["region"] + dates
        data.set_index("region", inplace=True)
        data.dropna(how="all", inplace=True)

        long_data = data.stack().reset_index()
        long_data.columns = ["region", "date", value_name]
        long_data = long_data.dropna(subset=[value_name])
        long_data["date"] = pd.to_datetime(long_data["date"])
        return long_data

    df_mar = read_demography(filename, "marriages")
    print(f"Загружено {len(df_mar)} записей о браках")

region_keywords = {
    "Москва": "Город Москва",
    "Санкт-Петербург": "Город Санкт-Петербург",
    "Московская область": "Московская область",
    "Краснодарский край": "Краснодарский край",
    "Ростовская область": "Ростовская область",
    "Республика Дагестан": "Республика Дагестан",
    "Республика Башкортостан": "Республика Башкортостан",
    "Республика Татарстан": "Республика Татарстан",
    "Свердловская область": "Свердловская область",
    "Челябинская область": "Челябинская область"
}

exact_regions = {}
for display, kw in region_keywords.items():
    matches = [r for r in df_mar["region"].unique() if kw in r]
    if matches:
        exact_regions[display] = matches[0]
    else:
        print(f"Предупреждение: регион '{kw}' не найден, пропускаем.")

print(f"Найдено регионов: {len(exact_regions)}")

df_annual = df_mar.copy()
df_annual["year"] = df_annual["date"].dt.year
df_annual = df_annual[df_annual["year"].between(2015, 2020)]

def calc_trend(series):
    x = series.index.values
    y = np.log(series.values)
    slope, _, _, _, _ = linregress(x, y)
    return slope * 100

trends = {}
for display, exact in exact_regions.items():
    annual = df_annual[df_annual["region"] == exact].groupby("year")["marriages"].sum()
    if len(annual) >= 5:
        trends[display] = calc_trend(annual)
    else:
        trends[display] = np.nan
        print(f"Недостаточно данных для {display}")

trend_df = pd.DataFrame(list(trends.items()), columns=["Регион", "Темп_год_%"])
trend_df = trend_df.dropna().sort_values("Темп_год_%", ascending=True)

print("\nСреднегодовые темпы снижения браков (2015–2020):")
print(trend_df.to_string(index=False))

values = trend_df["Темп_год_%"].values
max_idx = np.argmax(values)
min_idx = np.argmin(values)

colors = ['#3498db'] * len(trend_df)
colors[max_idx] = '#e74c3c'
colors[min_idx] = '#2ecc71'

plt.figure(figsize=(12, 8))
y_pos = np.arange(len(trend_df))
bars = plt.barh(y_pos, trend_df["Темп_год_%"], color=colors, edgecolor='black', alpha=0.8)

plt.yticks(y_pos, trend_df["Регион"], fontsize=10)

for bar in bars:
    width = bar.get_width()
    plt.text(width + 0.1, bar.get_y() + bar.get_height()/2,
             f'{width:.1f}%', va='center', fontsize=9, fontweight='bold')

plt.xlabel('Среднегодовой темп снижения, %', fontsize=12)
plt.title('Среднегодовая динамика браков в 10 крупнейших регионах России\nс 2015 по 2020 год', fontsize=14, fontweight='bold')
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.axvline(x=0, color='black', linestyle='-', linewidth=0.8)
plt.xticks([])

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime
from google.colab import files
from matplotlib.patches import Patch

try:
    df_divorces
except NameError:
    print("Загрузите файл с разводами (например, data (6).xls)")
    uploaded = files.upload()
    filename = list(uploaded.keys())[0]

    def read_demography(filepath, value_name):
        raw = pd.read_excel(filepath, sheet_name="Данные", header=None)
        years = raw.iloc[2, 1:].values
        months = raw.iloc[3, 1:].values

        cur_year = None
        filled_years = []
        for y in years:
            if pd.notna(y):
                cur_year = int(y)
            filled_years.append(cur_year)

        month_dict = {
            'январь':1, 'февраль':2, 'март':3, 'апрель':4, 'май':5, 'июнь':6,
            'июль':7, 'август':8, 'сентябрь':9, 'октябрь':10, 'ноябрь':11, 'декабрь':12
        }

        dates = []
        for y, m in zip(filled_years, months):
            if y is not None and pd.notna(m):
                m_str = str(m).strip().lower()
                month_num = month_dict.get(m_str, 1)
                dates.append(datetime(y, month_num, 1))
            else:
                dates.append(None)

        data = raw.iloc[4:].copy()
        data.columns = ["region"] + dates
        data.set_index("region", inplace=True)
        data.dropna(how="all", inplace=True)

        long_data = data.stack().reset_index()
        long_data.columns = ["region", "date", value_name]
        long_data[value_name] = pd.to_numeric(long_data[value_name], errors='coerce')
        long_data = long_data.dropna(subset=[value_name])
        long_data["date"] = pd.to_datetime(long_data["date"])
        return long_data

    df_divorces = read_demography(filename, "divorces")
    print(f"Загружено {len(df_divorces)} записей о разводах")

rus2020 = df_divorces[df_divorces["date"].dt.year == 2020].groupby(df_divorces["date"].dt.month)["divorces"].sum()
rus2020 = rus2020.sort_index()

months_ru = ['Янв','Фев','Мар','Апр','Май','Июн','Июл','Авг','Сен','Окт','Ноя','Дек']
x = range(1, 13)
y = rus2020.values

max_idx = np.argmax(y)
min_idx = np.argmin(y)

colors = ['#3498db'] * 12
colors[max_idx] = '#e74c3c'
colors[min_idx] = '#2ecc71'

plt.figure(figsize=(12, 6))
bars = plt.bar(x, y, color=colors, edgecolor='black', linewidth=0.8)

for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height + max(y)*0.02,
             f'{int(height):,}'.replace(',', ' '), ha='center', va='bottom', fontsize=9)

plt.xticks(x, months_ru, fontsize=11)
plt.xlabel('Месяц', fontsize=12)
plt.ylabel('Число разводов', fontsize=12)
plt.title('Количество разводов в 10 самых населенных регионах России за 2020 год', fontsize=14, fontweight='bold')
plt.grid(axis='y', linestyle='--', alpha=0.7)

legend_elements = [
    Patch(facecolor='#e74c3c', edgecolor='black', label='Максимум'),
    Patch(facecolor='#2ecc71', edgecolor='black', label='Минимум'),
    Patch(facecolor='#3498db', edgecolor='black', label='Остальные месяцы')
]
plt.legend(handles=legend_elements, loc='lower right')

plt.tight_layout()
plt.show()

print(f"Максимум разводов: {months_ru[max_idx]} – {int(y[max_idx]):,}".replace(',', ' '))
print(f"Минимум разводов: {months_ru[min_idx]} – {int(y[min_idx]):,}".replace(',', ' '))